## Simple Linear Regression or Univriate Regression

Import necessary libraries

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

Provide Data

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [3]:
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


Creating object for LinearRegression

In [4]:
model = LinearRegression()

Fitting the Model

In [5]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

Predict the score

In [6]:
r_squ = model.score(x,y)
print(r_squ)

0.715875613747954


In [7]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [8]:
y_predict = model.predict(x)
print(y_predict)

[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [9]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [10]:
y_new = model.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
